
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  # these are replica set labels
  labels:
    purpose: tolerations-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: tolerations-demo
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: tolerations-demo
        project: roboshop
    spec:
    node-selector:  
      kubernetes.io/hostname: ip-192-168-4-212.ec2.internal
    containers:
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: tolerations-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headles
spec:
  # if a service clusterIP then it is called as headless service
  clusterIP: None
  selector:
    purpose: tolerations-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      
